"""add is_emergency to distributions

Revision ID: 4a995223878e
Revises: 6e17a6bf8649
Create Date: 2026-07-03 16:32:43.527098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a995223878e'
down_revision: Union[str, None] = '6e17a6bf8649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributions', sa.Column('is_emergency', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributions', 'is_emergency')
    # ### end Alembic commands ###
